### ISSUE TITLE
Not working in Angular 14.2

### ISSUE THREAD

**Issue by cmschandan** [ngx-lottie/ngx-lottie#161]
## I am trying to view one shapes from lottie files but it's showing below errors in my application

`node_modules/ngx-lottie/lib/base.directive.d.ts:69:18 - error TS2707: Generic type 'ɵɵDirectiveDeclaration' requires between 6 and 8 type arguments.

69 static ɵdir: i0.ɵɵDirectiveDeclaration<BaseDirective, "[lottie]", never, { "options": "options"; "containerClass": "containerClass"; "styles": "styles"; }, { "animationCreated": "animationCreated"; "complete": "complete"; "loopComplete": "loopComplete"; "enterFrame": "enterFrame"; "segmentStart": "segmentStart"; "configReady": "configReady"; "dataReady": "dataReady"; "domLoaded": "domLoaded"; "destroy": "destroy"; "error": "error"; }, never, never, false, never>;
`
image

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected behavior

I added below code in my Angular HTML Template

`<ng-lottie [options]="options" (animationCreated)="created($event)" width="500px" height="600px" [styles]="styles" containerClass="moving-box"></ng-lottie>`

## Environment

<pre><code>
Libs:
- @angular/core version: 14.2.0
- ngx-lottie version: ^10.0.0

Browser:
- [ ] Chrome (desktop) version 112.0.5615.138
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 17.0.36  
- Platform:  Windows 

Others:

</code></pre>
